### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by wtliao** [royorel/FFHQ-Aging-Dataset#5] opened 2020-12-04 12:36 UTC
First of all, thanks a lot for sharing your nice work and dataset.  I have downloaded the dataset using pydrive . However, when I execute the `run_deeplap.py`, I have the following issues:

 Traceback (most recent call last):
  File "run_deeplab.py", line 100, in <module>
    main()
  File "run_deeplab.py", line 76, in main
    inputs=dataset[i]
  File "/data/scene_understanding/FFHQ-Aging/FFHQ-Aging-Dataset/data_loader.py", line 32, in __getitem__
    _img = Image.open(self.images[index]).convert('RGB')
  File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/PIL/Image.py", line 2944, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file 'ffhq_aging256x256/50000/50368.png'

I have also tried to open this image with skimage and opencv, and it failed. So I think the reason is that this image file is damaged. There are tens of images having the same issue, there indexes are:
1895, 7907, 9033, 20931, 22460, 24714, 28687, 44240, 52531, 54602, 58819, 62418, 62659, 62877
Note that, these are the image **indexes ** (i.e. i in line 74 in run_deeplap.py ) but not the image name.

To use all the dataset, could you send me these images? Thanks a lot in advance.

**Comment by royorel** [comment] 2020-12-04 15:42
@wtliao,  as you said, these images were probably not download properly, hence the image read error. Are you able to view them with any image viewer?

Unfortunately, we can't redistribute the FFHQ images as we do not own them and we might violate NVIDIA's license if we do that (some images can only be redistributed with full author credit). For the same reason, we are not hosting the images ourselves, but just provide a code to download them from NVIDIA's google drive. This ensures that the terms in the original FFHQ license are not violated.

If these are the only images that gone bad, here's what I would do. I would change line 339 in `download_ffhq_aging.py`
https://github.com/royorel/FFHQ-Aging-Dataset/blob/3b1931aa8badaad01d6e40c428696dfc566efcec/download_ffhq_aging.py#L339

And would only keep the entries that gone bad in the `specs` list, e.g. something like: 
```
bad images list = ['1895', '7907', '9033', '20931', '22460', '24714', '28687', '44240', '50368', '52531', '54602', '58819', '62418', '62659', '62877']
specs = [item['in_the_wild'] for key, item in json_data.items() if key in bad images list] + [license_specs['wilds']]
```

and rerun the `get_ffhq_aging.sh/bat` script. That should run pretty quickly as only a small amount of images need to be downloaded.

Once again, I'm sorry I can't distribute the images myself.

**Comment by wtliao** [comment] 2020-12-06 13:12
@royorel ， thanks a lot for your help. I have downloaded the damaged images again. However, the issue still exists and I cannot view these images using any image viewer. I check these images and find that all of them are in the size of 0 bytes. Maybe the problem is in the resource? Could you have a look whether they are normal on your side?
All these images are:
ffhq_aging256x256/50000/50368.png
ffhq_aging256x256/36000/36195.png
ffhq_aging256x256/46000/46607.png
ffhq_aging256x256/31000/31840.png
ffhq_aging256x256/09000/09744.png
ffhq_aging256x256/26000/26711.png
ffhq_aging256x256/40000/40199.png
ffhq_aging256x256/01000/01356.png
ffhq_aging256x256/48000/48866.png
ffhq_aging256x256/13000/13516.png
ffhq_aging256x256/62000/62815.png
ffhq_aging256x256/07000/07748.png
ffhq_aging256x256/07000/07630.png
ffhq_aging256x256/07000/07914.png

Thanks a lot again for your friendly and warm help.

**Comment by royorel** [comment] 2020-12-06 13:57
@wtliao I checked the in-the-wild folder in the NVIDIA google drive folder and the images were not removed from there. That means the the problem is not with the source, but with the download process.

One thing that could've happened, which I failed to mention in my first comment is that you need to delete the faulty images from the destination dir before running the script, otherwise, they will be marked as done by this line
https://github.com/royorel/FFHQ-Aging-Dataset/blob/3b1931aa8badaad01d6e40c428696dfc566efcec/download_ffhq_aging.py#L151 

And will be skipped in the download process. I will update the code to also check if the file size and/or md5sum match before marking a specs entry as done.

Generally speaking, the google drive interface is very problematic, as it can deny downloading a file due to daily quota limit and other reasons, which cannot be bypassed by the code. Using the pydrive interface mitigates a lot of these issues but not all of them. I know that this can be an unpleasant experience and I'm sorry I can't completely bypass these issues.

I will update you once I commit this fix.  

UPDATE: The fix is going to be tricker than I thought since the file size and md5sum information for the final output in the ffhq_aging directory is dependent on the desired output size which is a user input so storing these for every possible output is  problematic, especially if someone also changes some parameters in the `align_in_the_wild_image` function. The right thing to do is to compare the in-the-wild images file size & md5sum since this information is part of the json file, but these images are deleted after processing to save disk space (They take ~1TB of disk space), so comparing against them is also not possible. So for now, the best solution is to manually remove the faulty images and try to re-download them in the same way as my previous comment.

**Comment by wtliao** [comment] 2020-12-07 13:05
@royorel Thanks a lot for your swift reply. You are right, I must delete the damaged image before I redownload them. Now, these images are correct:). I guess the problem is caused by using pydrive. The download process was interrupted many times because of the error "too many files are opened". And the script is able to download from the breakpoint. However, the image file which is the breakpoint won't be redownloaded again (because the corresponding file has been created). Maybe you can provide a script for a sanity check that deletes and redownloads the incorrect images.

**Comment by royorel** [comment] 2020-12-07 16:28
@wtliao I just uploaded an updates that does exactly that. Damaged files will be re-downloaded and overwritten. This behavior will not be default since it will increase the runtime and is not needed when you download for the first time. If you want to use it, add the `--check_invalid_images` flag when you invoke `download_ffhq_aging.py`.

**Closed as completed by royorel** 2020-12-07 16:28 UTC
